# A file containing a list of collections to be installed.
# Usage:
# ansible-galaxy install -r requirements.yml
---
collections:
  - name: community.docker
  - name: community.general  # Required for apk, from_ini and supervisorctl modules.
  - name: community.windows
  - name: ansible.windows

roles:
  - name: ea31337.metatrader
    scm: git
    src: git+https://github.com/EA31337/ansible-role-metatrader.git
    version: v1.0.2
